### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by seyyah** [littlevgl/stm32f746_disco_no_os_atollic#11]
There is not releases in the "stm32f746_disco_no_os_atollic".

> @kisvegabor It would be really important for backward compatibility.

@kisvegabor can you send colloborator invitation?

:link: Reference: https://github.com/littlevgl/lv_examples/issues/12#issuecomment-430649820

**Comment by embeddedt** [comment]
@seyyah I've sent the invitation.

**Comment by seyyah** [comment]
I got and accept your invitation.

**Comment by seyyah** [comment]
## How to

```sh
git tag -a v6.0 025f2680e2d649df9cdd5bbce6cf1ad9816def19
git tag -a v5.3 78cf55374f02728484b045c75c2e6ec5a19883ce
git push origin --tags
```

## :camera: Releases
![image](https://user-images.githubusercontent.com/263237/61459828-462b7900-a976-11e9-9076-5c829f73e1ca.png)

## :clipboard: Reference
1. https://git-scm.com/book/en/v2/Git-Basics-Tagging
