### ISSUE TITLE
ADC values freeze after tft_init

### ISSUE THREAD

**Issue by tomtristan** [littlevgl/stm32f746_disco_no_os_atollic#5]
Hello!

I've been trying to port this library to my self-designed PCB with the same MCU (F746). Everything else seems to work so far, but not commenting out tft_init results in adc_buffer values freezing and hadc1 goes into errorcode - 6 and hdma_adc1  errorcode - 2.  As soon as i comment tft_init out, the adc values update every breakpoint(so constantly working), and obviously library wont start. 
Could you look into this? If one of you could try to use ADC1 with DMA on your discovery board, while enabling the library, does your ADC still continue to work?
I'm happy to provide everything to understand this problem better,

**Comment by embeddedt** [comment]
@tomtristan Not sure if you've solved this problem yet, but if you haven't, I'd be happy to test this for you if there's no hardware required besides the discovery board.

**Comment by tomtristan** [comment]
@embeddedt I think discovery board is enough to test this. You could try running attached CubeMX configuration on the discovery board, and see if your ADC freezes with this configuration(set the ADC DMA priority to low or medium, mine's set to very high(LvGL uses HIGH priority) because this bypassed/fixed this issue). I'm interested whether this issue is there for you too when having lower priority or not.
[FEST19_Dashensoorika_LVGL_try2.zip](https://github.com/littlevgl/stm32f746_disco_no_os_atollic/files/3010272/FEST19_Dashensoorika_LVGL_try2.zip)

**Comment by embeddedt** [comment]
@tomtristan Sorry, I haven't had a chance to try your file in detail yet. Limited time...

I looked at it before but it didn't appear to include all components, so I wasn't sure how to proceed. If I get a chance, I will give it another try.
