### ISSUE TITLE
Follow LittlevGL v6.0

### ISSUE THREAD

**Issue by seyyah** [littlevgl/stm32f746_disco_no_os_atollic#6]
## :white_check_mark: TODO

- [ ] Create branchs: 5.3, 6.0
- [ ] submodule updates
- [ ] lv_conf migration
- [ ] lv_ex_conf migration
- [ ] LittlevGL compilation error: https://github.com/littlevgl/lvgl/commit/38c55377c675f95d478c42a9942138bd379a48a1#r32999373

**Comment by embeddedt** [comment]
This one would be easy. As far as I can tell the source code for both Atollic and SW4STM32 is identical so it should be a matter of copying files and updating the submodules.

I don't have Atollic so I wouldn't be able to test it easily. Would someone else be willing to give it a test if I updated it based off SW4STM32?

**Comment by seyyah** [comment]
> This one would be easy. As far as I can tell the source code for both Atollic and SW4STM32 is identical

:+1: 

> so it should be a matter of copying files and updating the submodules.

Is my way correct?

```sh
stm32f746_disco_no_os_atollic⟫ cd lvgl
stm32f746_disco_no_os_atollic⟫ git pull
stm32f746_disco_no_os_atollic⟫ git checkout dev-6.0
```

In addition to we customize `lv_conf.h` and `lv_ex_conf.h` file.

> I don't have Atollic so I wouldn't be able to test it easily. Would someone else be willing to give it a test if I updated it based off SW4STM32?

I'm able to test on the stm32f745 disco board.

**Comment by embeddedt** [comment]
@seyyah 

> Is my way correct?

Yes, you just have to do that with `lv_examples` as well.

> In addition to we customize `lv_conf.h` and `lv_ex_conf.h` file.

Yes; you should be able to use the ones from the `sw4stm32` project with minimal or no changes.

> I'm able to test on the stm32f745 disco board.

Great!

**Comment by seyyah** [comment]
## Submodule update

```sh
git submodule -q foreach git pull -q origin dev-6.0
```
Edit: ~git submodule update --remote~

## :clipboard: Reference
1. https://stackoverflow.com/questions/1979167/git-submodule-update

**Comment by embeddedt** [comment]
#7 was merged so I will close this.
