### ISSUE TITLE
Graphics display incorrectly after power cycle

### ISSUE THREAD

**Issue by embeddedt** [littlevgl/stm32f746_disco_no_os_atollic#9]
After power cycling the board, numerous artifacts are visible on screen.

I don't see these when using SW4STM32, so something is different in the way Atollic initializes the hardware.

You won't see this behavior if your board was previously running a working program (i.e. the sw4stm32 project) and was not power cycled in between.

**Comment by kisvegabor** [comment]
It's really strange. I have a few questions:
- What if you reset the board with the Reset button?
- What if you add some delay at the beginning to be sure the display has woken up?
- Will the artifacts disappear later as you use the UI?
- Can you send a screenshot?

**Comment by embeddedt** [comment]
> What if you reset the board with the Reset button?

It will still work. It requires a complete power cycle (unplugging and plugging the board back in) to break.

> Will the artifacts disappear later as you use the UI?

No, they are persistent.

> What if you add some delay at the beginning to be sure the display has woken up?

It doesn't solve the issue.

I found that replacing the `SystemClock_Config` function with the one from the SW4STM32 project seemed to prevent the issue, which means it must be related to the clocking in the Atollic version.

> Can you send a screenshot?

It's a bit difficult for me to get one. Can you try running the Atollic project (`master` branch should have the issue)?

**Comment by kisvegabor** [comment]
> I found that replacing the SystemClock_Config function with the one from the SW4STM32 project seemed to prevent the issue, which means it must be related to the clocking in the Atollic version.

Maybe the MCU is overclocked?

> It's a bit difficult for me to get one. Can you try running the Atollic project (master branch should have the issue)?

Unfortunately, I don't have that board...

**Comment by embeddedt** [comment]
> Maybe the MCU is overclocked?

Quite possible. I'll investigate it soon.

**Comment by embeddedt** [comment]
I compared the two `SystemClock_Config` functions and didn't see a major difference between them.

Since both projects are targetting exactly the same configuration and board I just replaced the Atollic clock configuration with the SW4STM32 one.

That seems to have solved the problem.

**Comment by kisvegabor** [comment]
It should be fine for now, however, if someone uses CubeMX and re-generates   the project, the modification will be overwritten.
